Source/Code/Begin/Expenses.Web/Controllers/ReportsController.cs
namespace Expenses.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using Expenses.Web.Models;
    using Expenses.Web.Repository;

    [Authorize]
    public class ReportsController : Controller
    {
        private readonly IExpenseReportsRepository expenseReportRepository;
        private readonly IUserProfileRepository userProfileRepository;

        public ReportsController()
            : this(new ExpenseReportsRepository(), new UserProfileRepository())
        {
        }

        public ReportsController(IExpenseReportsRepository expenseReportRepository, IUserProfileRepository userProfileRepository)
        {
            this.expenseReportRepository = expenseReportRepository;
            this.userProfileRepository = userProfileRepository;
        }

        [HttpGet]
        public ActionResult Index(string status)
        {
            IEnumerable<ExpenseReport> reports;

            ViewBag.Status = status ?? "all reports";
            var userId = this.GetUserId();

            if (User.IsInRole("manager"))
            {
                reports = this.expenseReportRepository.GetEmployeesReports(userId, status, 0);
                ViewBag.Header = string.Format("{0} ({1})", string.IsNullOrEmpty(status) ? "All Reports" : status + " Reports", reports.Count());
            }
            else
            {
                reports = string.IsNullOrEmpty(status) ? this.expenseReportRepository.GetUserReports(userId) : this.expenseReportRepository.GetUserReports(userId, status);
                ViewBag.Header = string.Format("{0} ({1})", string.IsNullOrEmpty(status) ? "All Reports" : "Filtered by " + status + " status", reports.Count());
            }

            return View(reports);
        }

        [HttpPost]
        public JsonResult Index(ExpenseReport report)
        {
            return this.CreateOrUpdate(report);
        }

        [HttpGet]
        public ActionResult GetOrUpdate(int id)
        {
            var report = this.expenseReportRepository.GetReport(id);
            return View("Detail", report);
        }

        [HttpPut]
        public JsonResult GetOrUpdate(ExpenseReport report)
        {
            return this.CreateOrUpdate(report);
        }

        public ActionResult Edit(int id)
        {
            var report = this.expenseReportRepository.GetReport(id);
            return View(report);
        }

        [HttpPost]
        public ActionResult ApproveReject(int id, string comments, string action)
        {
            var report = this.expenseReportRepository.GetReport(id);
            if (report != null)
            {
                report.StatusId = ReportsContextInitializer.RejectedStatus;
                report.StatusId = "Approve".Equals(action) ? ReportsContextInitializer.ApprovedStatus : ReportsContextInitializer.RejectedStatus;
                report.Comments = comments;
                report.ApproverName = User.Identity.Name;
                this.expenseReportRepository.Save(report);
            }

            return RedirectToAction("GetOrUpdate", id);
        }

        public ActionResult New()
        {
            return View("Edit", new ExpenseReport());
        }

        public ActionResult Delete(int id)
        {
            this.expenseReportRepository.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public JsonResult Summary()
        {
            var result = this.expenseReportRepository.GetEmployeesReports(this.GetUserId(), "pending", 0);
            return Json(new { pending = result.Count() }, JsonRequestBehavior.AllowGet);
        }

        private JsonResult CreateOrUpdate(ExpenseReport report)
        {
            try
            {
                report.UserId = this.GetUserId();
                if (report.StatusId == ReportsContextInitializer.PendingStatus)
                {
                    report.Submitted = DateTime.Now;
                }

                this.expenseReportRepository.Save(report);
                return Json(new { success = true, reportId = report.Id });
            }
            catch (Exception)
            {
                return Json(new { error = "error" });
            }
        }

        private Guid GetUserId()
        {
            return this.userProfileRepository.GetProfile(User.Identity.Name).UserId;
        }
    }
}

Source/Code/Begin/Expenses.Web/Views/Reports/Detail.cshtml
@using Expenses.Web.Models
@model ExpenseReport
@{
    ViewBag.Title = "Detail";
}

<div class="breadcrumbs">
@if (User.IsInRole("manager"))
{
    @Html.ActionLink(this.Model.Status.Name, "Index", "Reports", new { status = this.Model.Status.Name }, null) <span>/</span> 
    @Model.User.FullName<span>/</span> 
    @Model.Name
}
else
{
    @Html.ActionLink("dashboard", "Index", "Home") <span>/</span>     
    @Html.ActionLink(this.Model.Status.Name, "Index", "Reports", new { status = this.Model.Status.Name }, null) <span>/</span>
    @Model.Name  
}
</div>

<h2>@this.Model.Name</h2>
<strong>Purpose:</strong> @this.Model.Purpose
<br />
<strong>Status:</strong> @this.Model.Status.Name
<br />
<strong>Owner:</strong> @(this.Model.User.FirstName + " " + this.Model.User.LastName)
<br />
<hr />

@if (!string.IsNullOrEmpty(this.Model.ApproverName))
{
    <strong>Approver:</strong> @(this.Model.ApproverName)
    <br />
}
@if (!string.IsNullOrEmpty(this.Model.Comments))
{
    <strong>Comments:</strong> @(this.Model.Comments)
    <br />
}

@if (!User.IsInRole("manager") && this.Model.Status.Name.Equals("Draft"))
{
    <div class="expenses-header">
        <a href="@Url.RouteUrl("Report", new { @id = this.Model.Id, action = "delete" })" class="delete-link delete-report">
            <img src="@Url.Content("~/Content/img/delete.png")" alt="Delete" width="14" height="14"/>Delete
        </a>
        <a href="@Url.RouteUrl("Report", new { @id = this.Model.Id, action = "edit" })" class="edit-link">
            <img src="@Url.Content("~/Content/img/edit.png")" alt="Edit" width="14" height="14"/>Edit
        </a>   
        <h3>Expenses</h3>
    </div>
} 
else
{
    <h3>Expenses</h3>
}

<table class="details shadow">
    <tr>
        <th>#</th>
        <th class="description">Description</th>
        <th>Expense Date</th>
        <th>Category</th>
        <th>Merchant</th>
        <th>Transaction Amount</th>
        <th>Receipt</th>
    </tr>
    @if (this.Model.Details.Count() > 0)
    {
        var details = this.Model.Details.ToArray();
        for (int i = 0; i < details.Length; i++)
        {
            var detail = details[i];
        <tr>
            <td>@(i + 1)</td>
            <td>@detail.Description</td>
            <td>@string.Format("{0:d}", detail.Date)</td>
            <td>@detail.Category</td>
            <td>@detail.Merchant</td>
            <td>@string.Format("{0:C}", detail.TransactionAmount)</td>
            @if (string.IsNullOrEmpty(detail.ReceiptUrl))
            {
                <td>N/A</td>
            }
            else
            {
                <td><a href="@detail.ReceiptUrl" class="receipt-attachment">View</a></td>
            }
        </tr>
        }
    }
    else
    {
        <tr>
            <td colspan="7">There are no expenses.</td>
        </tr>
    }
</table>
@if (User.IsInRole("manager"))
{
    if (this.Model.Status.Name.Equals("Pending"))
    {
    <form name="report-approve-form" id="report-approve-form" action="@Url.RouteUrl("Report", new { @id = this.Model.Id, action = "ApproveReject" })" method="post">
        @Html.LabelFor(m => m.Comments)<br />
        @Html.TextAreaFor(m => m.Comments, 5, 50, new { data_val = "true", data_val_required = "Comments are required." })
        @Html.ValidationMessageFor(m => m.Comments)<br/>
        @Html.Hidden("action")<br />
        <input type="button" value="Approve" class="approve button button-blue"/>
        <input type="button" value="Reject" class="reject button button-black"/>
    </form>
    }
}

Source/Code/Begin/Expenses.Web/Views/Reports/Edit.cshtml
@using Expenses.Web.Models
@model ExpenseReport

@{
    ViewBag.Title = this.Model.Id > 0 ? "Edit Report" : "New Report"; 
}
@if (this.Model.Id > 0)
{
    <div class="breadcrumbs">
        @Html.ActionLink("reports", "Index", "Reports") <span>/</span>
        @Html.ActionLink(this.Model.Status.Name, "Index", "Reports", new { status = this.Model.Status }, null) <span>/</span> 
        @this.Model.Name
    </div>
    <h2>@this.Model.Name</h2>
} else {
    <div class="breadcrumbs">
        @Html.ActionLink("reports", "Index", "Reports") <span>/</span>
        Add new Report
    </div>
    <h2>ADD NEW REPORT</h2>
}

<form name="expense-report-form" id="expense-report-form" action="/" method="post">
    <fieldset class="general">
        <legend>Expense Report Details</legend>
               
        @Html.LabelFor(i => i.Name)
        @Html.TextBoxFor(i => i.Name)
        @Html.ValidationMessageFor(i => i.Name)<br/>
    
        @Html.LabelFor(i => i.Purpose)
        @Html.TextBoxFor(i => i.Purpose)
        @Html.ValidationMessageFor(i => i.Purpose)<br/>
        
        @Html.HiddenFor(i => i.Id)
        @Html.Hidden("username", User.Identity.Name)
    </fieldset>
    
    <fieldset class="expenses" style="height:100%;overflow:auto">
        <legend>Expenses</legend>

        <div class="expenses-header">
        @if (!User.IsInRole("manager"))
        {
            <a href="#" class="add-new"><img src="@Url.Content("~/Content/img/add_new.png")" alt="Add New Expense" width="14" height="14"/>Add New Expense</a>
        }
            <h3>Expenses</h3>    
        </div>

        <table class="edit shadow">
            <tr>
                <th class="index">#</th>  
                <th class="date">Date</th>                  
                <th class="category">Category</th>
                <th class="description">Description</th> 
                <th class="merchant">Merchant</th>      
                <th class="billed-amount">Billed Amount</th>
                <th class="transaction-amount">Transaction Amount</th>
                @if (!User.IsInRole("manager"))
                {
                    <th class="actions">Actions</th>
                }
            </tr>
        @{
            var noExpenses = false;
            if (this.Model.Details != null && this.Model.Details.Count() > 0)
            {
                noExpenses = true;
                @Html.EditorFor(m => m.Details);
            } 
            
            <tr class="no-expense"><td colspan="@(User.IsInRole("manager") ? "7" : "8")" style="@(noExpenses ? "display:none;" : "")">There are no expenses for this report.</td></tr>
            
        }
    
        @{
            decimal total = 0;
            
            if (this.Model.Details != null && this.Model.Details.Count() > 0) 
            {
                total = this.Model.Details.Sum(i => i.TransactionAmount);  
            }
        }
        </table>
    </fieldset>
    <p class="total">
        <strong>Total: $ <span>@string.Format("{0:0.00}", total)</span></strong>
    </p>
    <div class="actions">
        <a href="#" class="button button-blue save-draft"><span>Save Draft</span></a>
        <a href="#" class="button button-blue submit"><span>Save and Submit</span></a>
        @if (this.Model.Id > 0)
        {
            <a href="@Url.RouteUrl("Report", new { @id = this.Model.Id, action = string.Empty })" class="button button-black discard"><span>Discard</span></a>
        }
        else 
        { 
            <a href="@Url.RouteUrl("Reports")" class="button button-black discard"><span>Discard</span></a>
        }        
    </div>
</form>

<!-- Attach Form Here -->

<script type="text/html" id="detail-template">
    @Html.Partial("EditorTemplates/ExpenseReportDetail", new ExpenseReportDetail() { Date = DateTime.Now })
</script>

Source/Code/Begin/Expenses.Web/Views/Reports/Index.cshtml
@using Expenses.Web.Models
@model IEnumerable<ExpenseReport>

@{
    ViewBag.Title = "Reports";
}
@if (@User.IsInRole("manager")) {
    if (!string.IsNullOrEmpty(Request["status"]) && Request["status"].Equals("pending", StringComparison.InvariantCultureIgnoreCase))
    {
        <h1 class="toapprove">Pending Approval</h1>
    }
    else
    {
        <h1 class="reports">Reports</h1>
    }
}
else
{
    <h1 class="reports">My Reports</h1>
}

<hr/>
<h3>@ViewBag.Header</h3>

<table class="reports shadow">
    <tr>
    @if (User.IsInRole("manager"))
    {
        <th class="user">User</th>
    }
        <th class="report-name">Name</th>
        <th class="submitted">Submitted Date</th>
        <th class="status">Status</th>
        <th class="total">Total</th>
    </tr>

@if (this.Model.Count() > 0)
{
    foreach (var report in this.Model)
    {
        <tr>
            @if (User.IsInRole("manager"))
            {
                <td>@(report.User.FirstName + " " + report.User.LastName) </td>
            }
            <td><a href="@Url.RouteUrl("Report", new { @id = report.Id, action = string.Empty })">@report.Name</a></td>
            <td>@string.Format("{0:d}", report.Submitted) </td>
            <td>@report.Status.Name</td>
            <td>@string.Format("{0:C}", report.Details.Sum(d => d.TransactionAmount))</td>
        </tr>
    }
}
else
{
    var colspan = User.IsInRole("manager") ? "6" : "5";
    <tr>
        <td colspan="@colspan">No reports were found.</td>
    </tr>
}
</table>

@if (!User.IsInRole("manager"))
{
    <div class="actions">
        <a href="@Url.Action("new", "reports")" class="button button-black">
            <span>Add New Report</span>
        </a>
    </div>
}